### ISSUE TITLE
Just added new twitch.core I get error

### ISSUE THREAD

**Issue by dariux1x** [SReject/mTwitch#11]
I get this http://prntscr.com/ayan2l

**Comment by SReject** [comment]
Are you using mIRC or AdiIRC?
What version?
Do you have other scripts loaded?

**Comment by dariux1x** [comment]
Mirc 7.43, I was always using your Json, core and groupchat, yesturday I changed to new one and I get those errors

**Comment by SReject** [comment]
the error you are getting refers to the line `set -e $+(%,$cid,mTwitch.CapAcceptHalt) $true`. for whatever reasons the 'set' command is being ignored and the `-e $+(...` stuff is being sent to the server.

Do you have other scripts or aliases, besides mine loaded?

**Comment by dariux1x** [comment]
All my scripts that I'm using [mirc scripts.zip](https://github.com/SReject/mTwitch/files/243832/mirc.scripts.zip)

**Comment by SReject** [comment]
I'm not seeing anything in my script or your others that would be causing this issue. Nor are others experiencing this issue.

Just a side note: You no longer need groupchat.mrc, its been incorporated into the core.mrc
