### ISSUE TITLE
mTwitch.DisplayName.mrc Now Needs a "Client_ID" to Connect to API

### ISSUE THREAD

**Issue by Blasman** [SReject/mTwitch#14]
On line 7 of mTwitch.DisplayName.mrc, due to new Twitch requirements, a "client id" is now required for the script to read from the Twitch API. https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.ek6t4qpra

**Comment by SReject** [comment]
This is now fixed as of commit 85d01ff8eed05d67577cc07d861f07d1896adb6c and the [release](https://github.com/SReject/mTwitch/releases/tag/v1.0.1) has been updated with the fix

Going to leave this issue open for a few days to make sure the fix works. For anyone that stumbles upon this issue, please give me feedback to whether it works or not
