### ISSUE TITLE
Alt. DisplayName script to remove localized names

### ISSUE THREAD

**Issue by zembtach** [SReject/mTwitch#20]
I'm wondering if you can create an alternative version of **mTwitch.DisplayName.mrc** that removes localized names for people that want that? Or maybe make it an option somehow?

The problem I have is that if I use the mIRC script, it will _only_ show the localized name, since that is the display name.

On Twitch it normally shows both the localized name and the username, and a lot of people (including myself) also use [BTTV](https://github.com/night/BetterTTV/blob/master/src/modules/disable_localized_names/index.js) to completely remove the localized name.

The problem with having _only_ the localized name, for me at least, is that it makes it really difficult to moderate a channel with lots of Korean chatters, because I can't type out their name, or tab-complete it.

Here's an example: 비서91 (bsuh91)
Here's his [Twitch API](https://api.twitch.tv/kraken/users/90456573?client_id=e8e68mu4x2sxsewuw6w82wpfuyprrdx&api_version=5)
Here's his parseline:
`@badges=premium/1;color=#1E90FF;display-name=비서91;emotes=;id=83baf952-c9b7-4323-844a-91d62a6cec95;mod=0;room-id=36625500;sent-ts=1496084548967;subscriber=0;tmi-sent-ts=1496084549486;turbo=0;user-id=90456573;user-type= :bsuh91!bsuh91@bsuh91.tmi.twitch.tv PRIVMSG #rebebbiz :test`

BetterTTV can just replace the name with what's inside the brackets, so that's easy for them. But for IRC we probably need to test the display name for non-alphanumeric characters.

That above parseline would normally look like this: `<비서91> test`
But I think I fixed it now to this: `<bsuh91> test`

I changed [the code](https://github.com/SReject/mTwitch/blob/ee25aa472c65965969ae950630365d40cde158fd/mTwitch.DisplayName.mrc#L23) to this, and it works fine for me:
```
  if ($mTwitch.isServer) {
    %dnick = $remove($mTwitch.MsgTags(%tags, display-name), $chr(32), $cr, $lf)
    if ($regex(%dnick,/\W/)) {
      .parseline -it %tags $+(:, %nick, %param)
    }
    elseif (%dnick !== $null && %dnick !=== %nick) {
      .parseline -it %tags $+(:, %dnick, %param)
    }
  }
```
I figured if `%dnick` is empty it will return 0 anyway, so there's no need for other checks than the regex for localized check.

I removed that `user-name=` insertion just to make it easier to read. But maybe you'd also want to add a `localized-name=` thing or something?

I'm sure more people would be happy with a change like this, so I thought I'd share :)

**Comment by SReject** [comment]
I've added a command to toggle using the localized nick; this feature has not been tested so I'll leave this issue open until its confirmed to be working:

`/mTwitch.Localization @State`  
`@State` can be `on`, `off`, `enable`, `disable` or `toggle`

**Comment by SReject** [comment]
I've added a command to mTwitch.DIsplayName.mrc for toggling the usage of localized nicks. I have yet to test the feature so will leave this ticket open until its confirmed the feature is working as intended.

```mIRC  
/mTwitch.Localization @State  
@State can be on, off, enable, disable or toggle  
    If on or enable localized nicks WILL be displayed
    If off or disable localized nicks WILL NOT be displayed
```

*Just a note here; For realtime discussions on features, improvements or suggestions, feel free to drop by #MircHelp on twitch*

**Comment by zembtach** [comment]
Seems to be working just as planned. I love it. Thank you. Your solution is much more elegant. ;)
This is mIRC:
![mirc](https://cloud.githubusercontent.com/assets/10890923/26563470/d621428e-44d2-11e7-825b-120a573f121c.png)
And these are the same lines in Twitch - localization is removed from the middle line as expected.
![twitch](https://cloud.githubusercontent.com/assets/10890923/26563480/fb308b52-44d2-11e7-956c-030f1a677d6a.png)

You can try yourself by browsing any Korean streams: https://www.twitch.tv/directory/all/ko

> _Just a note here; For realtime discussions on features, improvements or suggestions, feel free to drop by #MircHelp on twitch_

Awesome. For next time :)
