### ISSUE TITLE
Whisper handling

### ISSUE THREAD

**Issue by DreadfullyDespized** [SReject/mTwitch#21]
I recently looked over your parseline on how you get the whispers that are directed to the bot.  Though I am quite curious if you have any ideas or examples as to how the bot would respond to that whisper.

The goal I am working towards is that if someone whispers a command !birthday for instance.  To the bot that it would react the same as if the user whispered it in the channel.

Thank you sincerely for your time and your effort on this.

**Comment by SReject** [comment]
Unless something has changed, you should be able to use mIRC's default privmsg handling:

```
on *:TEXT:!birthday:?:{
   msg $nick Its not my birthday
}
```


Be wary of certain twitch settings; dependant on the user's settings they my not receive the reply

**Comment by DreadfullyDespized** [comment]
Well after trying multiple times I get the response from tmi.twitch.tv No user matching that login.  When I attempt to reply to a whisper.  Though it works when the user is in the channel.

I have tried the following examples.

`on *:TEXT:!sounds:?: {
  PRIVMSG $chan /w $nick Sound Cmds: $sqlsounds($nick)
  PRIVMSG /w $nick Sound Cmds: $sqlsounds($nick)
}`
`on *:TEXT:!sounds:?,#dreadfullydespized: {
  PRIVMSG $chan /w $nick Sound Cmds: $sqlsounds($nick)
  PRIVMSG /w $nick Sound Cmds: $sqlsounds($nick)
}`

Though if I have it just the channel and then it sees the channel message and then replies with the whisper perfectly every time.

**Comment by DreadfullyDespized** [comment]
Nevermind my last statement I figured it out.  Thank you again!!!
