### ISSUE TITLE
Combine all modules into one script?

### ISSUE THREAD

**Issue by SReject** [SReject/mTwitch#6]
Instead of having multiple scripts, should I just go ahead and merge core+all modules into a single script?

**Comment by cmgangrel** [comment]
Personally I would combine them

**Comment by itskeyes** [comment]
Combine them all.

**Comment by SReject** [comment]
Due to twitch now allowing for whispers to be sent on the same connection as the IRC interface, whispers are no incorporated into mTwitch.Core.mrc. Users should uninstall mTwitch.GroupChat.mrc then update the core
