### ISSUE TITLE
mTwitch.GroupChat.mrc can't connect to group chat

### ISSUE THREAD

**Issue by darioriccioni** [SReject/mTwitch#7]
Hi. I just restarted my mIRC bot and got this message:

[mTwitch->GroupChat] Connection to Twitch Group-Chat server lost; attempting to reconnect...

I noticed the script has been updated 9 days ago and updated it, but I still get the message above.

**Comment by darioriccioni** [comment]
I just noticed this message, I don't know if it's related to this script...

Invalid CAP command

**Comment by SReject** [comment]
Please note that you will also need to update mTwitch.Core.Mrc

**Comment by darioriccioni** [comment]
I updated it as well, I even tried to unload mTwitch.GroupChat.mrc but I still get that "Invalid CAP command" message, so it seems there's a problem with the Core script too. And BTW after I updated the scripts I started having those problems and on mIRC even if I join the channel I can't see other people and other people in chat can't see me/the bot.

**Comment by SReject** [comment]
Try unloading all scripts but `JSONForMirc.mrc`, `mTwitch.Core.mrc`, and `mTwitch.GroupChat.mrc` then restart mIRC. Connect to twitch using:

```
/server irc.chat.twitch.tv:80 oauth:[OAUTH_TOKEN_HERE] -i [USER_NAME_HERE]
```

Does the problem presist? (If you'd like, we can move this conversation to mirchelp's stream chat on twitch)

**Comment by SReject** [comment]
This is related to issues with twitch. Once the migration of group-chat servers to AWS is complete and normalizes I will update the whisper script to make use of changes
